name: Run Python Script

on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:   # allows manual run
 # schedule:
 #   - cron: '0 8 * * *'
 
jobs:
  run-script:
    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        shell: pwsh
        run: |
          data_path="RawData/Location_101.csv"
          naming_path="RawData/Location_101_renamed.csv"
          base_name='B-065-000-000'
          python --version
          #python src/script.py --name Ricky --age 30
          python src/scil_renaming.py --data_path data_path --naming_path naming_path --base_name base_name
    
